[project]
name = "fastxmltodict"
version = "1.24.1"
description = "A fast and lightweight library for converting XML to a Python dictionary."
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }
authors = [{ name = "MichaelScofield" }]
requires-python = ">=3.6"
dependencies = []
