[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hexopy"
version = "0.2.0"
description = "HexOPy üõ†Ô∏èüêç ‚Äì Hexagonal Architecture for Python"
readme = "README.md"
authors = [{ name = "Javier Avila njavilas", email = "njavilas2015@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "colorama==0.4.6",
    "pydantic==2.10.6",
    "pytest==8.3.4",
    "asyncpg==0.30.0",
    "uvicorn==0.34.0",
    "aerich",
    "tortoise-orm",
    "aiosqlite",
    "fastapi"
]

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
hexopy = "hexopy.cli:main"

[project.urls]
"Homepage" = "https://github.com/njavilas2015/HexOPy"
"Bug Tracker" = "https://github.com/njavilas2015/HexOPy/issues"
