[tool.poetry]
name = "web360"
version = "0.1.0"
description = "Tools for AI Agents"
authors = ["Lukas Korganas"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
build = "^1.2.2.post1"
twine = "^6.1.0"


[tool.poetry.group.dev.dependencies]
twine = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
