[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "secret_2fa"
version = "1.0.3"
description = "A Python library for handling secure 2fa authentication using Pyppeteer."
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Nguyễn Minh Đức", email = "dancntt7@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
    "pyppeteer"
]
