[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wygr"
version = "0.0.7"
authors = [
  { name="sai", email="yenishettysai@gmail.com" },
]
description = "This is a Travel Planner App built with Streamlit that generates personalized travel itineraries based on user input"
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]


[tool.hatch.metadata]
allow-direct-references = true  

[project.urls]
Homepage = "https://github.com/saikrisnaa/wygr"
Issues = "https://github.com/saikrisnaa/wygr"
