[build-system]
requires = [ "setuptools>=61.0", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "vicentin"
version = "0.6.4"
description = "Personal collection of algorithms."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [ "numpy", "scipy", "jax",]
classifiers = [ "Programming Language :: Python :: 3", "Operating System :: OS Independent",]
[[project.authors]]
name = "Felipe Vicentin"
email = "hello@a.vicentin.xyz"

[project.license]
text = "MIT License"

[project.urls]
Homepage = "https://github.com/Vinschers/algorithms"

[tool.setuptools.packages.find]
where = [ "src",]
exclude = [ "tests", "docs",]
