[project]
name = "parsdantic"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SergiFuster", email = "sergifusterdura@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "jsonref>=1.1.0",
    "pydantic>=2.10.6",
]

[project.scripts]
parsdantic = "parsdantic:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
