[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jsonhandlerdb"
version = "0.0.2"
authors = [
  { name="Keagan Landfried", email="keaganlandfried@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}

[project.urls]
Homepage = "https://github.com/Zennara/JsonHandler"
Issues = "https://github.com/Zennara/JsonHandler/issues"