[project]
name = "scsu"
version = "0.2"
authors = [
    { name="Gonard", email="gonard@fastmail.jp" },
]
description = "Standard Compression Scheme for Unicode"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",

    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",

    "License :: OSI Approved :: MIT License",

    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE.txt"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://gitlab.com/gonard/scsu"
Issues = "https://gitlab.com/gonard/scsu/issues"