[package]
name = "rust-vocab"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_vocab"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
