[project]
name = "pyrouting"
version = "0.1.5"
description = "Mobility data routing"
authors = [
    {name = "osrokas", email = "rokasptr@gmail.com>"}
]
repository = "https://github.com/mevplanas/mobility-data-routing"
readme = "README.md"
packages = [
    { include = "pyrouting", from = "." }
]
requires-python = ">=3.10"
dependencies = [
    "geopandas (>=1.0.1)",
    "networkx (>=2.2.3)",
    "tqdm (>=4.66.2)",
    "osmnx (>=1.9.1)",
    "pandas (>=2.2.0)",
    "contextily (>=1.6.2)",
    "geojson (>=3.1.0)",
    "fastparquet (>=2024.5.0)",
    "pyarrow (>=17.0.0)",
    "scipy (>=1.14.1)"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"