[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pykomodo"
version = "0.0.4"
description = "A chunking library"
dependencies = ["pathspec"]
authors = [{ name = "oha" }]

[project.scripts]
komodo = "pykomodo.command_line:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["pykomodo*"]

[tool.setuptools]
zip-safe = false