[tool.poetry]
name = "norm-benchmark"
version = "0.12.0"
description = "coNstructiOn pRoject Manager"
authors = ["Bruno Chicelli <b.rosilva1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.6.1"
transformers = "^4.49.0"
sentence-transformers = "^3.4.1"
fire = "^0.7.0"
streamlit = "^1.42.2"
boto3 = "^1.36.26"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.0"
flake8 = "^7.1.2"

pandas-stubs = "^2.2.3.241126"
types-tqdm = "^4.67.0.20241221"
boto3-stubs = "^1.36.26"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
norm-benchmark = "norm_benchmark.norm_cli:run"