# This file is placed in the Public Domain.
 
[build-system]
requires = [
    'setuptools>=43.0.0',
    'wheel'
]
build-backend = 'setuptools.build_meta'


[project]
name = 'nixm'
version = "71"
authors = [
    {name = 'Bart Thate', email = 'bthate@dds.nl' },
]
readme = "README.rst"
description = 'NIXM'
license = { text='Public Domain'}
dependencies = [
    'nixt',
]
classifiers=[
    'Development Status :: 4 - Beta',
    'License :: Public Domain',
    'Operating System :: Unix',
    'Programming Language :: Python :: 3',
    'Topic :: Utilities'
]


[project.urls]
'home'   = 'https://pypi.org/project/nixm'
'bugs'   = 'https://github.com/otpcr/nixm/issues'
'source' = 'https://github.com/otpcr/nixm'


[tool.setuptools]
script-files = [
    'bin/nixm',
]
packages = [
    'nixm',
    'nixm.modules'
]
