[project]
name = "tiktokrocket"
version = "0.1.1"
description = ""
authors = [
    {name = "eugconrad"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "setuptools (>=75.8.0,<76.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "selenium (>=4.28.1,<5.0.0)",
    "selenium-wire (>=5.1.0,<6.0.0)",
    "selenium-stealth (>=1.0.6,<2.0.0)",
    "fake-useragent (>=2.0.3,<3.0.0)",
    "undetected-chromedriver (>=3.5.5,<4.0.0)",
    "blinker (==1.7.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
