[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aws-connect-cli"
version = "0.1.0"
description = "A CLI tool to manage AWS services"
authors = [{ name = "Jayasurya A", email = "techie4coffee@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
dependencies = [
    "boto3>=1.36.26",
    "build>=1.2.2.post1",
    "inquirer>=3.4.0",
    "inquirerpy>=0.3.4",
    "rich>=13.9.4",
    "setuptools>=75.8.0",
    "tabulate>=0.9.0",
    "twine>=6.1.0",
    "typer>=0.15.1",
]

[project.scripts]
aws = "aws_connect.cli:main"


