[tool.poetry]
name = "redis-tagged-cache"
version = "0.11.0"
description = ""
authors = ["Fabien MARTY <fabien.marty@botify.com>"]
readme = "README.md"
packages = [{ include = "rtc" }]

[tool.poetry.dependencies]
python = "^3.7"
redis = ">=3.2.0"

[tool.poetry.group.test.dependencies]
pytest = [
    { version = "^8.3", python = ">=3.9" },
    { version = "~7.4", python = "<3.9" },
]
tomli = [{ version = "~2.0", python = "<3.9" }]
packaging = [
    { version = "24.0", python = "<3.9" },
    { version = ">= 24.2", python = ">=3.9" },
]

[tool.poetry.group.lint.dependencies]
ruff = { version = "^0.8", python = ">=3.9" }
mypy = { version = "^1.13", python = ">=3.9" }

[tool.poetry.group.doc.dependencies]
import-linter = { version = "^2.1", python = ">=3.9" }
mkdocstrings = { extras = ["python"], version = "^0.27", python = ">=3.9" }
mkdocs-material = { python = ">=3.9", version = "^9.5.47" }
mkdocs-awesome-pages-plugin = { python = ">=3.9", version = "^2.9.3" }
jinja-tree = { python = ">=3.9", version = ">=0.6.1" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
exclude = "^site"
