[tool.poetry]
name = "openfund-taker"
version = "1.2.2"
description = "Openfund-taker"
authors = []
readme = "README.md"
packages = [
    { include = "taker", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.9"
ccxt = "^4.4.26"
requests = "^2.27.1"
pydantic-settings = "^2.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-mock = "^3.14.0"
pytest-asyncio = "^0.23.3"
TA-Lib = "^0.6.3"


[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[tool.pytest.ini_options] # mandatory section name
addopts = "-vs --no-header --no-summary"
log_cli = 1
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s.%(msecs)03d - %(filename)s:%(lineno)d - %(funcName)s - %(levelname)s - %(message)s"
log_cli_datefmt = "%Y-%m-%d-%H:%M:%S"
testpaths = [ 
    "tests",
]

[tool.poetry.scripts]
openfund-taker = "taker.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

