[project]
name = "simple_keystore"
version = "0.6.1"
description = "\"A simple encrypted key storage, now with a simple throttler (using Redis)\""
authors = [
    { name = "Paul", email = "paul@nowfree.org" },
]
dependencies = [
    "cryptography>=43.0.0",
    "fakeredis>=2.27.0",
    "freezegun>=1.5.1",
    "pytest>=8.3.4",
    "python-redis-rate-limit>=0.0.10",
    "redis>=5.2.1",
    "tabulate>=0.9.0",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Repository = "https://github.com/eyecantell/simple_keystore"
Issues = "https://github.com/eyecantell/simple_keystore/issues"

[project.scripts]
manage_simple_keys = "simple_keystore.manage_simple_keys:main"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 120

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.pdm]
distribution = true
package-dir = "src"

[tool.pytest.ini_options]
pythonpath = [
    "src",
]

[dependency-groups]
test = [
    "pytest>=8.0.0",
]
