[build-system]
requires = ["setuptools"] # REQUIRED if [build-system] table is used
build-backend = "setuptools.build_meta" # If not defined, then legacy behavior can happen.

[project]
name = "snom_analysis" # REQUIRED, is the only field that cannot be marked as dynamic.
version = "0.1.17" # REQUIRED, although can be dynamic
description = "Package for displaying and manipulating SNOM and AFM data"
readme = "README_short.rst"
requires-python = ">=3.9"
license = { text = "GPL-3.0-or-later" }
keywords = ["snom", "afm", "near-field", "atomic force microscopy"]
authors = [{ name = "H.-J. Schill", email = "hajo.schill@acetovit.de" }]
maintainers = [
  { name = "H.-J. Schill", email = "hajo.schill@acetovit.de" },
]
classifiers = [
  # Specify the Python versions you support here. In particular, ensure
  # that you indicate you support Python 3. These classifiers are *not*
  # checked by "pip install". See instead "requires-python" key in this file.
  "Programming Language :: Python :: 3 :: Only",
]
dependencies = ["scipy==1.13.*", "matplotlib==3.9.*", "mpl_point_clicker==0.4.*", "matplotlib_scalebar==0.8.*", "imageio==2.34.*", "colorcet==3.1.*", "scikit-image==0.24.*"]

[project.urls]
# "Homepage" = "https://github.com/pypa/sampleproject"
# "Bug Reports" = "https://github.com/pypa/sampleproject/issues"
# "Funding" = "https://donate.pypi.org"
# "Say Thanks!" = "http://saythanks.io/to/example"
"Source" = "https://github.com/pypa/sampleproject/"
"Documentation" = "https://snom-analysis.readthedocs.io/en/latest/"

# This is configuration specific to the `setuptools` build backend.
# If you are using a different build backend, you will need to change this.
# [tool.setuptools]
# If there are data files included in your packages that need to be
# installed, specify them here.
# package-data = { "sample" = ["*.dat"] }