[project]
name = "xls_is_for_corporate"
version = "1.0.1"
description = "XLS is for corporate, convert it to something else"
authors = [
    {name = "Felipe QuÃ©cole",email = "felipequecole@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl (>=3.1.5,<4.0.0)",
    "click (>=8.1.8,<9.0.0)",
    "rich (>=13.9.4,<14.0.0)",
    "questionary (>=2.1.0,<3.0.0)",
    "xlrd (>=2.0.1,<3.0.0)",
    "importlib-metadata (>=8.6.1,<9.0.0)"
]

[project.scripts]
xlsifc = "xls_is_for_corporate.xlsifc:cli"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

