[build-system]
requires = [ "setuptools>=46.4.0", "wheel>=0.36.2"]
build-backend = "setuptools.build_meta"

[project]
name = "acme_s3"
version = "0.0.3"
description = "Efficient access to S3"
readme = "README.md"
classifiers = [ "Programming Language :: Python :: 3.12", ]
dependencies = [ "python-dotenv", "boto3", "tqdm", "backoff", "botocore", "pandas"]

[[project.authors]]
email = "guner.stan@gmail.com"

[project.scripts]
as3 = "acme_s3._main:main"

[project.urls]
homepage = "https://example.com"
repository = "https://example.com"

[project.optional-dependencies]
dev = [
    "pytest", # for testing
    "uv", # for venv
    "mkdocs", # for documentation
    "mkdocs-material", # theme for mkdocs
    "mkdocstrings[python]", # mkdocs plugin to generate API docs from sources
    "jupyterlab", # for jupyter notebooks
    "isort", # for sorting imports
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["acme_s3"]
# https://github.com/astral-sh/uv/issues/9513#issuecomment-2519527822
license-files = []
# [tool.setuptools.package-data]