[project]
name = "custom-repr"
version = "1.2.0"
description = "A lightweight Python library to automatically generate clean __repr__ methods for all your user-declared classes."
authors = [
    { name = "Pedro Fernandes da Silva", email = "paca.fs@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
keywords = ["repr", "string representation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"