[project]
name = "piretry"
version = "0.1.2"
description = "A decorator to retry a function if it raises an exception"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "setuptools>=75.8.0",
    "twine>=6.1.0",
    "wheel>=0.45.1",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
