[project]
name = "cmpal"
version = "0.1.2"
description = ""
authors = [
    {name = "jinyang628",email = "chenjinyang4192@gmail.com"},
    {name = "suveenE",email = "suveen.ellawela@u.nus.edu"}
]
readme = "README.md"
requires-python = ">=3.12, <4.0"



[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
isort = "^6.0.0"
autoflake = "^2.3.1"


[tool.poetry.dependencies]
setuptools = "^75.8.0"
ollama = "^0.4.7"
pydantic = "^2.10.6"
simple-term-menu = "^1.6.6"
colorama = "^0.4.6"
[tool.black]
line-length = 100

[tool.isort]
line_length = 100
wrap_length = 100
multi_line_output = 3
profile = "black"
include_trailing_comma = true

[tool.poetry.scripts]
"cmpal" = "cmpal.main:main" 

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
